### ISSUE TITLE
httpWebRequest.AllowAutoRedirect forced to false

### ISSUE THREAD

**Issue by ewmccarty** [darrylwhitmore/NScrape#22]
NScrape.WebClient 

			// We shall handle redirects by hand so that we may capture cookies and properly
			// handle login forms.
			//
			// Automating Web Login With HttpWebRequest
			// https://www.stevefenton.co.uk/Content/Blog/Date/201210/Blog/Automating-Web-Login-With-HttpWebRequest/
			/// TODO remove this 
#if !NETSTANDARD1_5
			httpWebRequest.AllowAutoRedirect = false;
#endif

Forcing httpWebRequest.AllowAutoRedirect = false; throws and exception for a Redirect URI. Is the exception just a way of indicating the Redirect occurred, allowing for alternate processing?

**Comment by darrylwhitmore** [comment]
Hi Erik, sorry for the delay! There should definitely not be any exception thrown here.

I've taken a look, and first, let me verify that you are using NScrape.sln, and **not** NScrape.Core.sln. I think this must be the case, as otherwise, the line you mention would not be compiled, but just want to verify.

Next, in my testing with NScrape.sln, using the RedirectWebResponseAutoRedirectTest() in class WebResponseTests in the NScrape.Test project, I saw an exception, but it was on the line after the one you referenced; it was on the line setting the user agent:

`httpWebRequest.Headers[HttpRequestHeader.UserAgent] = UserAgent;`

The exception here was _**The 'User-Agent' header must be modified using the appropriate property or method.**_

I'm assuming this must be your exception as well as mine. It looks to me as if this issue was introduced when this line was changed in  commit ea3b9124 for some of the .Net Core conversion work. I have a fix, it's just a matter of using an #ifdef to use the prior line of code when not building for .Net Core. It allows the test method mentioned above to complete successfully.

For now, I'll hold off on committing my fix so that you can comment on my assumptions above. Also, I'd like @qmfrederik to review this and give his thoughts.

Thanks for finding this issue and reporting it!

**Comment by darrylwhitmore** [comment]
I went ahead, let me know if any issues. It's commit 262cf08.
